/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.labassignment1;


import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ayseguleyrice
 */
public class NewJFrame extends JFrame implements MouseListener {
    
    int x,y,i;
    JLabel label =new JLabel();


    public void SetLayout(int x, int y, int w, int l, Component c){
        c.setLocation(x, y);
        c.setSize(w, l);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   	{   
            Container con = getContentPane();
            setLayout(null);
            SetLayout(10, 10, 70, 20, label);
            con.add(label); 
            this.setSize(1000,500);
            this.setResizable(false);
            this.setVisible(true);
            this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            addMouseListener(this);	
	}
	public void paint(Graphics g)
	{
           super.paint(g);
		g.setColor(Color.WHITE);
		g.fillArc(300,50,400,400,1000,2000);
		g.setColor(Color.BLACK);
		g.drawLine(0, 250, 1000, 250);
		g.drawLine(500, 0, 500, 500);
		g.drawString("(0,0)",501,265);
		g.drawString("1",601,265); 
		g.drawString("-1",401,265); 
		g.drawString("2",701,265); 
		g.drawString("-2",301,265); 
		g.drawString("3",801,265); 
		g.drawString("-3",201,265); 
		g.drawString("1",503,165);
		g.drawString("-1",503,365);
		g.drawString("2",503,65);
		g.drawString("-2",503,465);
                
		g.drawOval(x-2,y-2,4,4);
		
		
               
                

		g.setColor(Color.cyan);
                
		for (i = 2 ; i < 400 ; i += 5){
                    g.drawLine(300+i,50 , 300+i, 450);
		}
                g.drawOval(300,50,400,400);
                
		g.setColor(Color.BLACK);
                g.drawOval(300,150,201,201);
                g.setColor(Color.WHITE);
                g.fillOval(300,150,200,200);
                
                label.setText( ((double)x-500)/100+"  "+((double)y-250)/-100 );
             
	
                
		
                
        }
    @Override
	public void mouseClicked (MouseEvent e) {
		x = e.getX();
		y = e.getY();		
		
		if ((y >= 50 && y <= 400 && x >= 300) & x <= 650){
                    JOptionPane.showMessageDialog(null, "Inside");
                }    
                else{
                    JOptionPane.showMessageDialog(null, "Outside");
                }
                    
                repaint();
	}
        
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		new NewJFrame();
	}
        
    @Override
	public void mouseEntered(MouseEvent arg0) {	
        }
	@Override
	public void mouseExited(MouseEvent arg0)  {	
        }
	@Override
	public void mousePressed(MouseEvent arg0) {
	}
	@Override
	public void mouseReleased(MouseEvent arg0){ 
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

